### ISSUE TITLE
Nested label not working with view component

### ISSUE THREAD

**Issue by mateuszbialowas** [ViewComponent/view_component#1760]
### Steps to reproduce
Create view component
```
    <%= render Shared::Inputs::ToggleComponent.new(object_name: f, method: :debit_enabled,
                                                   value: advertiser.wallet.debit_enabled,
                                                   label_text: t('.debit_enabled')) %>
```
```
class Shared::Inputs::ToggleComponent < ViewComponent::Base
  attr_reader :object_name, :method, :value, :label_text
  def initialize(object_name:, method:, value:, label_text:)
    @object_name = object_name
    @method = method
    @value = value
    @label_text = label_text
  end

end
```
```
<%= object_name.label method.to_sym, class: 'relative inline-flex items-center cursor-pointer' do %>
  <%= object_name.check_box method.to_sym, class: 'sr-only peer', checked: value %>
  <div class="w-11 h-6 bg-gray peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary_light rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
  <%= content_tag :span, label_text, class: 'ml-3 text-sm font-medium text-gray_dark' %>
<% end %>

```
Input, div and span should be nested but it does not. 
![CleanShot 2023-05-29 at 13 48 35](https://github.com/ViewComponent/view_component/assets/58574619/3aab5323-c01b-46d9-8ed3-34815e3b2bdb)

### Expected behavior

It should be nested like this:
![CleanShot 2023-05-29 at 13 50 24](https://github.com/ViewComponent/view_component/assets/58574619/cf817714-cb8a-4ddd-9486-d23eb76e74de)

### Actual behavior
Input, div and span should be nested inside label. 

![CleanShot 2023-05-29 at 13 52 55](https://github.com/ViewComponent/view_component/assets/58574619/55fa2990-4f1b-42d5-b5c0-b318842127b3)

**Backtrace**:

### System configuration
**Rails version**:
Rails 7.0.4
**Ruby version**:
ruby '3.1.0'

**Gem version**:
    view_component (2.74.1)

**Comment by Spone** [comment]
Hi! Please try enabling the [capture_compatibility_patch_enabled](https://viewcomponent.org/api.html#configuration) option, it should fix this issue.

**Comment by mateuszbialowas** [comment]
First I created new file for configuration:
```
# config/initializers/view_components.rb
Rails.application.configure do
  config.view_component.capture_compatibility_patch_enabledasd = true
end
```
I didn't resolved the problem. 

Then I added 
```
  config.view_component.capture_compatibility_patch_enabledasd = true

```
into 
config/environments/development.rb
But it also didn't fix the problem.

I also updated view component to     
view_component (2.82.0)

I restarted the app and still have the problem with rendering nested label.

**Comment by Spone** [comment]
@mateuszbialowas there seem to be a typo in your code:

```diff
-  config.view_component.capture_compatibility_patch_enabledasd = true
+  config.view_component.capture_compatibility_patch_enabled = true
```

**Comment by reeganviljoen** [comment]
@mateuszbialowas  do you know if the change  @Spone recommended has fixed your issue.

**Comment by mateuszbialowas** [comment]
I created file
config/initializers/view_component.rb
```
Rails.application.configure do
  config.view_component.capture_compatibility_patch_enabledasd = true
end
```
And now it is working. Thank you.

**Comment by mateuszbialowas** [comment]
Sorry, the problem still occurs with the form helpers. 
https://github.com/mateuszbialowas/ogloradar/pull/20/files

I created PR with my implementation. Maybe it will be easier to debug.

**Comment by Spone** [comment]
The [related PR](https://github.com/mateuszbialowas/ogloradar/pull/20) having been closed, I'm closing this.
