### ISSUE TITLE
Wrong I18n Scope used for slots in nested components in Ruby on Rails

### ISSUE THREAD

**Issue by henrikbjorn** [ViewComponent/view_component#2513]
In our application after upgrading to the new major version 4 we are seeing issues with how i18n scopes in our rails application is resolved when used with components.

We have a table component with the following api that uses 3 levels of nesting in the component.

``` erb
<# app/views/test/index.html.erb %>
  <%= render(TableComponent.new) do |table| %>
    <% table.with_row do |row| %>
      <% row.with_cell do %>
        <%= t('.hello') %>
      <% end %>
    <% end %>
  <% end %>
```

Previously this would be resolved to `test.index.hello` i18n key. After our upgrade it will try `table_component.hello` instead.

Recently there was merged something that looked like a fix for this on the main branch. But it dosen't resolve the issue.

Curiously it works if the nested is only 2 levels and not 3 as in my example (at least on the main branch)

### Steps to reproduce
Here is a single file test case that shows the bug https://gist.github.com/henrikbjorn/71bfad72e8810d4ac3eae2223c67d493

Running it will fail with

```
Fetching https://github.com/viewcomponent/view_component.git
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Run options: --seed 17537

# Running:

F

Finished in 0.012763s, 78.3515 runs/s, 156.7030 assertions/s.

  1) Failure:
SlotI18nTest#test_t('.key')_in_nested_slot_should_use_view's_i18n_scope [test.rb:77]:
Expected 'test.index.hello' but got: <table><tr><td>      Hello from table
</td></tr></table>.
Expected # encoding: ASCII-8BIT
#    valid: true
"<table><tr><td>      Hello from table\n</td></tr></table>" to include "Hello from view".

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

I have created a fix locally for our application, which added to the test case https://gist.github.com/henrikbjorn/689b8295ed5dd29797a876d5ac06db7f will make the test pass 

```
Fetching https://github.com/viewcomponent/view_component.git
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Run options: --seed 46458

# Running:

.

Finished in 0.012941s, 77.2738 runs/s, 154.5476 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

The fix as a module, not sure if it is good enough for a PR, since I am not really familiar with view component internals

``` ruby
module VirtualPathFix
  def render_in(view_context, &block)
    current_virtual_path = view_context.instance_variable_get(:@virtual_path)
    stored_original = view_context.instance_variable_get(:@__vc_original_view_virtual_path)
    is_view_path = current_virtual_path && !current_virtual_path.to_s.include?("component")

    @__vc_original_view_virtual_path = if is_view_path && current_virtual_path != stored_original
      current_virtual_path
    else
      stored_original
    end

    view_context.instance_variable_set(:@__vc_original_view_virtual_path, @__vc_original_view_virtual_path)
    super
  end

  def with_original_virtual_path
    view_context.instance_variable_set(:@virtual_path, @__vc_original_view_virtual_path)
    yield
  ensure
    view_context.instance_variable_set(:@virtual_path, virtual_path)
  end
end
```

### Expected behavior
I would expect the i18n key to be `test.index.hello`

### Actual behavior
The key is is resolved to `table_component.hello`

**Backtrace**:

### System configuration
**Rails version**: Latest 8.1 release

**Ruby version**: 3.4.7

**Gem version**: tested with latest main and latest 4.0

**Comment by gstokkink-bex** [comment]
We are also seeing issues with the resolution of partial translation keys in nested components after upgrading to Rails 8.1.1 and View Component 4.1.1. This is not exactly the same issue as in the OP, but also translations-related. It looks like the `virtual_path` is not correctly reset for nested renders sometimes.

**Comment by henrikbjorn** [comment]
@gstokkink Curious to see if the fix I included works

**Comment by gstokkink-bex** [comment]
@henrikbjorn unfortunately not 😄 With that patch we get dozens of test failures on missing translations, instead of a single one.

**Comment by gstokkink-bex** [comment]
@joelhawksley FYI, seems like the refactors for ViewComponent 4 broke some edge-case translations stuff. Looks `virtual_path` related.

**Comment by gstokkink-bex** [comment]
Might get fixed by https://github.com/ViewComponent/view_component/pull/2520.

**Comment by joelhawksley** [comment]
Fixed by #2520.

**Comment by gstokkink-bex** [comment]
@joelhawksley unfortunately it looks like `virtual_path` is still not set properly for deeply nested components:

```
Minitest::UnexpectedError:         RuntimeError: Cannot use t(".title") shortcut because path is not available
            /Users/work/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/actionview-8.1.2/lib/action_view/helpers/translation_helper.rb:135:in 'ActionView::Helpers::TranslationHelper#scope_key_by_partial'
            /Users/work/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/actionview-8.1.2/lib/action_view/helpers/translation_helper.rb:89:in 'ActionView::Helpers::TranslationHelper#translate'
            /Users/work/.rbenv/versions/3.4.6/lib/ruby/gems/3.4.0/gems/view_component-4.2.0/lib/view_component/translatable.rb:96:in 'ViewComponent::Translatable#translate'
```

This worked fine in ViewComponent 3.24.

**Comment by gstokkink-bex** [comment]
Ah, looks like the virtual path for the _view_ that uses the component is now always used when looking up partial i18n keys within a component's class, instead of the virtual path for the component's class. In other words, the i18n context of the view is used, instead of that of the component class. For instance, we have a `DesignSystem::Forms::TranslatableField::LegendComponent` component that has a `t('.title')` call in one of its methods. Before ViewComponent 4, this i18n key would be looked up as `design_system.forms.translatable_field.legend_component.title`, after ViewComponent 4 the i18n key that is being looked up is suddenly `en.design_system.styleguides.forms.examples.localized_field_with_translation_service.title` if the component is used in a view called `design_system/app/views/design_system/styleguides/forms/examples/_localized_field_with_translation_service.html.haml`. Thus, the exact i18n key depends on the name of the view that happens to use the component. That doesn't seem right? Or is this expected behaviour @joelhawksley? That basically means that shorthand i18n keys are not usable inside component classes anymore.

**Comment by thomasbrus** [comment]
It seems that relative translations inside a component rely on `__vc_i18n_backend`, which is only created if [sidecar translations](https://github.com/ViewComponent/view_component/blob/11cf3c9fc924901ea7cbe3db0e73752c66b2c53e/lib/view_component/translatable.rb#L31-L35) are present.

Interestingly, the same relative translation does work with regular (non sidecar) translations if placed in the template:

```yaml
# config/locales/en.yml
en:
  my_module:
    example_component:
      hello: "Hello world!"
```

```erb
<%# app/components/my_module/example_component.html.erb %>
<%= t(".hello") %>
```

This is because of [this line](https://github.com/ViewComponent/view_component/blob/11cf3c9fc924901ea7cbe3db0e73752c66b2c53e/lib/view_component/translatable.rb#L96):

```ruby
#=> en.my_module.example_component.hello
return @view_context.translate(key, **options) unless __vc_i18n_backend
```

But when that translation is moved to the component, it can lead to unexpected results 😄 .

Since now the translation is looked up in the original view that renders the component (not the component template).

So either use component relative translation + sidecar, or if you place the relative translation in the template, you can go either way (regular or sidecar translation).

**Comment by joelhawksley** [comment]
@gstokkink at a high level, there was no intention of changing this behavior in ViewComponent 4. As GitHub does not meaningfully use i18n, I have been fairly hands-off with that part of the framework. 

Would you be up for writing a test case and fix that restores the functionality from v3.x?

**Comment by gstokkink-bex** [comment]
@joelhawksley kind of swamped right now, but maybe I can find the time next week, no promises 😄

**Comment by mhenrixon** [comment]
This seems to pretty reliably fix the problem for us: 

```ruby
# ViewComponent 4.x has an issue where the virtual_path captured for slots
# is the component's virtual_path instead of the calling view's virtual_path.
#
# When a view renders a component with a block:
#   = render Cards::CardComponent.new do |c|
#     - c.with_tabs do
#       = t(".users")  # This needs the VIEW's virtual_path, not the component's
#
# The problem is that by the time __vc_set_slot is called, render_in has already
# set @virtual_path to the component's virtual_path. The slot captures this wrong
# path, causing I18n shortcuts like t(".key") to fail.
#
# This patch ensures slots capture @old_virtual_path (the view's path) instead
# of the current @virtual_path (the component's path).
#
# Related issues:
# - https://github.com/ViewComponent/view_component/issues/49
# - https://github.com/ViewComponent/view_component/issues/1258
# - https://github.com/ViewComponent/view_component/issues/2513

Rails.application.config.to_prepare do
  require "view_component"
  require "view_component/slotable"

  # Guard against future ViewComponent versions that may change the private
  # __vc_set_slot API this patch relies on
  vc_version = Gem::Version.new(ViewComponent::VERSION::STRING)
  unless vc_version >= Gem::Version.new("4.1.0") && vc_version < Gem::Version.new("4.4.0")
    raise "view_component_virtual_path_fix expects ViewComponent 4.1.x–4.3.x, " \
          "found #{ViewComponent::VERSION::STRING}. Verify the patch is still needed " \
          "(see https://github.com/ViewComponent/view_component/issues/2513) " \
          "and compatible before updating the version guard."
  end

  ViewComponent::Slotable.module_eval do
    private def __vc_set_slot(slot_name, slot_definition = nil, *args, **kwargs, &block)
      slot_definition ||= self.class.registered_slots[slot_name]
      slot = ViewComponent::Slot.new(self)

      if block
        slot.__vc_content_block = block
        # Use @old_virtual_path (the calling view's path) instead of the
        # current view_context's @virtual_path (which is the component's path)
        slot.__vc_content_block_virtual_path = @old_virtual_path

      end

      if slot_definition[:renderable]
        component_instance = slot_definition[:renderable].new(*args, **kwargs)
        slot.__vc_component_instance = component_instance
        # Propagate the calling view's virtual_path so nested components
        # can resolve relative I18n keys through the full slot chain
        if @old_virtual_path && component_instance.is_a?(ViewComponent::Base)
          component_instance.instance_variable_set(:@old_virtual_path, @old_virtual_path)
        end
      elsif slot_definition[:renderable_class_name]
        component_instance =
          self.class.const_get(slot_definition[:renderable_class_name]).new(*args, **kwargs)
        slot.__vc_component_instance = component_instance
        if @old_virtual_path && component_instance.is_a?(ViewComponent::Base)
          component_instance.instance_variable_set(:@old_virtual_path, @old_virtual_path)
        end
      elsif slot_definition[:renderable_function]
        # Use `bind(self)` to ensure lambda is executed in the context of the
        # current component. This is necessary to allow the lambda to access helper
        # methods like `content_tag` as well as parent component state.
        renderable_function = slot_definition[:renderable_function].bind(self)
        renderable_value =
          if block
            renderable_function.call(*args, **kwargs) do |*rargs|
              with_captured_virtual_path(@old_virtual_path) do
                view_context.capture(*rargs, &block)
              end
            end
          else
            renderable_function.call(*args, **kwargs)
          end

        # Function calls can return components, so if it's a component handle it
        if renderable_value.respond_to?(:render_in)
          slot.__vc_component_instance = renderable_value
          if @old_virtual_path && renderable_value.is_a?(ViewComponent::Base)
            renderable_value.instance_variable_set(:@old_virtual_path, @old_virtual_path)
          end
        else
          slot.__vc_content = renderable_value
        end
      end

      @__vc_set_slots ||= {}

      if slot_definition[:collection]
        @__vc_set_slots[slot_name] ||= []
        @__vc_set_slots[slot_name].push(slot)
      else
        @__vc_set_slots[slot_name] = slot
      end

      slot
    end
  end
end
```

Hope that helps

**Comment by joelhawksley** [comment]
@mhenrixon might I interest you in attempting a fix PR? We don't use i18n at GitHub so I'm unable to dedicate time to writing a fix.

**Comment by joelhawksley** [comment]
I spent some time trying to reproduce this today, but couldn't. Please open a PR with a failing test for the issue.
